### PR TITLE
Test test

### PR DESCRIPTION
**Pull request by drosofff**
@bgruening not to merge but just to show you that the test passes but the container does not work

### CODE REVIEW

**Comment by drosofff** [comment]
See https://travis-ci.org/galaxyproteomics/docker-galaxyp/builds/243258606#L793

**Comment by bgruening** [comment]
Interesting, but Galaxy is working, the tests are installing tools, run tools, upload data ... where do you see problems? I will look into it, thanks for reporting!

**Comment by drosofff** [comment]
wow Sh... my command docker run was improperly mapping ports... Sorry sorry.
Well, I'll see, but the docker galaxy instance is supposed to work with `rabbitmq    FATAL` ?...

**Comment by bgruening** [comment]
Oh, @drosofff is this still valid. Missed it completely.

**Comment by drosofff** [comment]
@bgruening I have no idea either :-) I remember I switched off the rabbitmq install in the playbook at some point.

**Comment by bgruening** [comment]
mh, ok I will track this in the base image and will try to look at it over Xmas.
Thanks!

**Pull request closed without merging**
